# Generated by Django 4.2.11 on 2024-03-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0002_data_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data_store',
        ),
    ]
